### ISSUE TITLE
NullPointerException on start

### ISSUE THREAD

**Issue by daviddelamo** [1tontech/intellij-spring-assistant#2]
Hi, i've installed this plugin today using the version from 11 april. When IntelliJ starts throws the a exception:

```
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataContainerInfo.getContainerFile(MetadataContainerInfo.java:66)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataContainerInfo.newInstances(MetadataContainerInfo.java:90)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.computeNewContainersToProcess(SuggestionServiceImpl.java:219)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.reindexModule(SuggestionServiceImpl.java:440)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$null$2(SuggestionServiceImpl.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reIndex$3(SuggestionServiceImpl.java:110)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by prog110** [comment]
Can you check whether you are seeing this error even after restart? I'm not sure how to reproduce this error as I am not receiving this

**Comment by markusadelsberger** [comment]
Hi,

I'm having the exact same Exception, after every restart.

Can I send you any other Logs? I'm using Idea 2019.1.3 Community Edition.

Thanks!

```
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataContainerInfo.getContainerFile(MetadataContainerInfo.java:66)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataContainerInfo.newInstances(MetadataContainerInfo.java:90)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.computeNewContainersToProcess(SuggestionServiceImpl.java:219)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.reindexModule(SuggestionServiceImpl.java:440)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$null$2(SuggestionServiceImpl.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:945)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reIndex$3(SuggestionServiceImpl.java:110)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
