### ISSUE TITLE
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation

### ISSUE THREAD

**Issue by uigdwunm** [1tontech/intellij-spring-assistant#20]
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
 at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
 at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:756)
 at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:708)
 at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:465)
 at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:298)
 at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:105)
 at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:93)
 at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:30)
 at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:86)
 at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClasses(JavaFileManagerImpl.java:73)
 at com.intellij.psi.impl.PsiElementFinderImpl.findClasses(PsiElementFinderImpl.java:62)
 at com.intellij.psi.impl.JavaPsiFacadeImpl.findClassesWithoutJvmFacade(JavaPsiFacadeImpl.java:157)
 at com.intellij.psi.impl.JavaPsiFacadeImpl.findClassesWithJvmFacade(JavaPsiFacadeImpl.java:128)
 at com.intellij.psi.impl.JavaPsiFacadeImpl.findClasses(JavaPsiFacadeImpl.java:120)
 at com.intellij.psi.impl.file.PsiPackageImpl.findAllClasses(PsiPackageImpl.java:203)
 at com.intellij.psi.impl.file.PsiPackageImpl.getCachedClassesByName(PsiPackageImpl.java:193)
 at com.intellij.psi.impl.file.PsiPackageImpl.findClassByShortName(PsiPackageImpl.java:270)
 at com.intellij.psi.impl.file.PsiPackageImpl.processDeclarations(PsiPackageImpl.java:310)
 at com.intellij.psi.impl.source.resolve.JavaResolveUtil.processImplicitlyImportedPackages(JavaResolveUtil.java:239)
 at com.intellij.psi.impl.source.JavaDummyHolder.processDeclarations(JavaDummyHolder.java:112)
 at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUti

**Comment by CrazyCoder** [comment]
https://youtrack.jetbrains.com/issue/IDEA-266660

**Comment by marchosius** [comment]
i have met same problem 😢

but I have fixed this problem by add *.json pattern in File Types

becasue of this setting make spring-boot-autoconfigure META-INFO/spring-configuration-metadata.json not been recognized

![QQ图片20210416011435](https://user-images.githubusercontent.com/48839423/114912330-73120600-9e52-11eb-9112-937556806182.png)
