### ISSUE TITLE
IndexNotReadyException

### ISSUE THREAD

**Issue by donnerpeter** [1tontech/intellij-spring-assistant#9]
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:81) VCS
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:787) VCS
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:745) VCS
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:725) VCS
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:519) VCS
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:374) VCS
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:107) VCS
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:95) VCS
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:47) VCS
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:87) VCS
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:122) VCS
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:44) VCS
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:110) VCS
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:87) VCS
	at com.intellij.psi.util.InheritanceUtil.isInheritor(InheritanceUtil.java:94) VCS
	at com.intellij.psi.util.InheritanceUtil.isInheritor(InheritanceUtil.java:85) VCS
	at in.oneton.idea.spring.assistant.plugin.misc.PsiCustomUtil.isClassSameOrDescendantOf(PsiCustomUtil.java:287)
	at in.oneton.idea.spring.assistant.plugin.misc.PsiCustomUtil.isMap(PsiCustomUtil.java:277)
	at in.oneton.idea.spring.assistant.plugin.misc.PsiCustomUtil.getSuggestionNodeType(PsiCustomUtil.java:203)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.updateGroupType(MetadataNonPropertySuggestionNode.java:546)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.setGroup(MetadataNonPropertySuggestionNode.java:445)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.addChildren(MetadataNonPropertySuggestionNode.java:236)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.addGroupsToIndex(SuggestionServiceImpl.java:605)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.buildMetadataHierarchy(SuggestionServiceImpl.java:459)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.processContainers(SuggestionServiceImpl.java:412)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.reindexModule(SuggestionServiceImpl.java:449)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$null$8(SuggestionServiceImpl.java:154)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:796) VCS
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reindex$9(SuggestionServiceImpl.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238) VCS
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by aiqency** [comment]
Same here after upgrading to:

**IntelliJ IDEA 2020.3 (Community Edition)
Build #IC-203.5981.155, built on November 30, 2020
Runtime version: 11.0.9+11-b1145.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16**

**Comment by eltonsandre** [comment]
https://github.com/1tontech/intellij-spring-assistant/issues/18#issuecomment-770574762
